[tox]
envlist = py310, py311, py312, py313, py314


[pytest]
testpaths = tests
addopts = --verbose

[testenv]
dependency_groups = test
commands = {envbindir}/pytest  --basetemp={envtmpdir}/pytest {posargs}

[testenv:docs]
changedir=docs
dependency_groups = docs
commands=
    {envbindir}/sphinx-build -d {envtmpdir}/doctrees source {temp_dir}/docs/html -W -b html
